apiVersion: v2
name: deployment-service
description: Krateo PlatformOps Deployment Service
type: application
icon: "https://github.com/krateoplatformops/community/blob/main/logos/black/icon.svg"

version: 1.2.27
appVersion: 1.2.25

dependencies:
  - name: helm-chart-library
    version: 0.1.7
    repository: http://charts.krateo.io

maintainers:
  - name: Mauro Sala
    email: mauro.sala@kiratech.it
    url: https://krateo.io
  - name: Luca Sepe
    email: luca.sepe@kiratech.it
    url: https://www.kiratech.it
